"use client";
import {useEffect,useMemo,useState} from "react";
import MetricCard from "@/components/MetricCard";
import type {AppDB,Empresa,Visita} from "@/types";
import {emptyDB,loadDB,saveDB} from "@/lib/storage";

type View="inicio"|"empresas"|"visitas"|"visita";
const labels:Record<string,string>={nomeFantasia:"Nome fantasia",razaoSocial:"Razão social",situacao:"Situação cadastral",cnae:"CNAE",cnaeDescricao:"Descrição do CNAE",tipo:"Tipo de estabelecimento",logradouro:"Logradouro",numero:"Número",complemento:"Complemento",bairro:"Bairro",cep:"CEP",municipio:"Município",uf:"UF",telefone:"Telefone",email:"E-mail",responsavel:"Responsável"};
const hoje=()=>{const n=new Date(),o=n.getTimezoneOffset();return new Date(n.getTime()-o*60000).toISOString().slice(0,10)};
const fdata=(d:string)=>d?new Date((d.length===10?d+"T12:00:00":d)).toLocaleDateString("pt-BR"):"—";

export default function Home(){
 const [db,setDb]=useState<AppDB>(emptyDB),[ready,setReady]=useState(false),[view,setView]=useState<View>("inicio");
 const [showEmpresaForm,setShowEmpresaForm]=useState(false),[showVisitaForm,setShowVisitaForm]=useState(false);
 const [visitaAtualId,setVisitaAtualId]=useState<string|null>(null),[criandoVisita,setCriandoVisita]=useState(false);
 const [msg,setMsg]=useState(""),[loading,setLoading]=useState(false);
 const [form,setForm]=useState({cnpj:"",nomeFantasia:"",razaoSocial:"",situacao:"",cnae:"",cnaeDescricao:"",tipo:"Outro",logradouro:"",numero:"",complemento:"",bairro:"",cep:"",municipio:"",uf:"",telefone:"",email:"",responsavel:""});
 const [vf,setVf]=useState({data:hoje(),responsavel:"",observacoes:""});

 useEffect(()=>{const s=loadDB();const vs=(s.visitas||[]).map((v:any)=>({id:v.id,empresaId:v.empresaId,data:v.data||hoje(),status:v.status==="Concluída"?"Concluída":"Em andamento",responsavel:v.responsavel||"",observacoes:v.observacoes||"",progresso:typeof v.progresso==="number"?v.progresso:(v.status==="Concluída"?100:0),criadoEm:v.criadoEm||v.data||new Date().toISOString()})) as Visita[];setDb({...s,visitas:vs});setReady(true)},[]);
 useEffect(()=>{if(ready)saveDB(db)},[db,ready]);

 const atual=db.empresaAtualId?db.empresas[db.empresaAtualId]:undefined;
 const visitaAtual=visitaAtualId?db.visitas.find(v=>v.id===visitaAtualId):undefined;
 const empresaVisita=visitaAtual?db.empresas[visitaAtual.empresaId]:undefined;
 const visitas=useMemo(()=>[...db.visitas].sort((a,b)=>(b.criadoEm||b.data||"").localeCompare(a.criadoEm||a.data||"")),[db.visitas]);

 async function buscar(){const c=form.cnpj.replace(/\D/g,"");if(c.length!==14){setMsg("Informe um CNPJ com 14 dígitos.");return}setLoading(true);setMsg("Buscando...");try{const r=await fetch(`/api/cnpj/${c}`),d=await r.json();if(!r.ok)throw new Error(d.error||"Não encontrado");setForm(f=>({...f,cnpj:d.cnpj||c,nomeFantasia:d.nome_fantasia||"",razaoSocial:d.razao_social||"",situacao:d.descricao_situacao_cadastral||"",cnae:String(d.cnae_fiscal||""),cnaeDescricao:d.cnae_fiscal_descricao||"",logradouro:d.logradouro||"",numero:d.numero||"",complemento:d.complemento||"",bairro:d.bairro||"",cep:d.cep||"",municipio:d.municipio||"",uf:d.uf||"",telefone:d.ddd_telefone_1||"",email:d.email||""}));setMsg("Empresa encontrada. Confira os dados.")}catch(e){setMsg(e instanceof Error?e.message:"Falha na consulta")}finally{setLoading(false)}}
 function salvarEmpresa(){const id=form.cnpj.replace(/\D/g,"")||crypto.randomUUID();const emp:Empresa={id,...form,nomeFantasia:form.nomeFantasia||form.razaoSocial||"Sem nome",criadoEm:new Date().toISOString()};setDb(o=>({...o,empresaAtualId:id,empresas:{...o.empresas,[id]:emp}}));setShowEmpresaForm(false);setView("empresas")}
 function novaVisita(){if(!atual){setView("empresas");return}setVf({data:hoje(),responsavel:"",observacoes:""});setShowVisitaForm(true);setView("visitas")}
 function salvarVisita(){if(!atual||criandoVisita)return;setCriandoVisita(true);const v:Visita={id:crypto.randomUUID(),empresaId:atual.id,data:vf.data||hoje(),status:"Em andamento",responsavel:vf.responsavel.trim(),observacoes:vf.observacoes.trim(),progresso:0,criadoEm:new Date().toISOString()};setDb(o=>({...o,visitas:[v,...o.visitas]}));setShowVisitaForm(false);setVisitaAtualId(v.id);setView("visita");setTimeout(()=>setCriandoVisita(false),500)}
 function continuar(id:string){const v=db.visitas.find(x=>x.id===id);if(!v)return;setDb(o=>({...o,empresaAtualId:v.empresaId}));setVisitaAtualId(id);setView("visita")}
 function concluir(id:string){setDb(o=>({...o,visitas:o.visitas.map(v=>v.id===id?{...v,status:"Concluída",progresso:100}:v)}))}
 function reabrir(id:string){setDb(o=>({...o,visitas:o.visitas.map(v=>v.id===id?{...v,status:"Em andamento",progresso:Math.min(v.progresso||0,90)}:v)}))}
 function excluir(id:string){if(!window.confirm("Excluir esta visita? Esta ação não pode ser desfeita."))return;setDb(o=>({...o,visitas:o.visitas.filter(v=>v.id!==id)}));if(visitaAtualId===id){setVisitaAtualId(null);setView("visitas")}}

 return <div className="min-h-screen bg-[#f4f7fb]">
  <header className="bg-[#17365D] text-white"><div className="mx-auto max-w-7xl px-4 py-4 flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><div className="text-xl font-extrabold">MBP Expert AI</div><div className="text-xs text-blue-100">Sistema Operacional para Consultoria em Segurança dos Alimentos • v2.1.1</div></div>{atual&&<div className="rounded-xl bg-white/10 px-4 py-2"><div className="text-[10px] font-extrabold uppercase text-blue-100">Empresa ativa</div><div className="font-extrabold">{atual.nomeFantasia}</div></div>}</div></header>
  <div className="mx-auto max-w-7xl p-4">
   <nav className="mb-4 flex gap-2"><button onClick={()=>setView("inicio")} className="rounded-xl bg-slate-200 px-4 py-2 font-bold">Início</button><button onClick={()=>setView("empresas")} className="rounded-xl bg-slate-200 px-4 py-2 font-bold">Empresas</button><button onClick={()=>setView("visitas")} className="rounded-xl bg-[#17365D] px-4 py-2 font-bold text-white">Visitas</button></nav>

   {showEmpresaForm?<section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="text-2xl font-extrabold">Nova empresa</h2><p className="text-sm text-slate-500">Digite o CNPJ para buscar os dados automaticamente.</p></div><button onClick={()=>setShowEmpresaForm(false)} className="rounded-xl bg-slate-100 px-3 py-2 font-bold">Fechar</button></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-xs font-bold text-slate-500">CNPJ</span><div className="flex gap-2"><input className="w-full rounded-xl border p-3" value={form.cnpj} onChange={e=>setForm({...form,cnpj:e.target.value})}/><button onClick={buscar} className="rounded-xl bg-slate-900 px-4 font-bold text-white">{loading?"...":"Buscar"}</button></div></label>{Object.entries(form).filter(([k])=>k!=="cnpj").map(([k,v])=><label key={k}><span className="mb-1 block text-xs font-bold text-slate-500">{labels[k]||k}</span><input className="w-full rounded-xl border p-3" value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div>{msg&&<div className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">{msg}</div>}<button onClick={salvarEmpresa} className="mt-4 w-full rounded-xl bg-[#2F5597] p-3 font-extrabold text-white">Salvar empresa</button></section>
   :showVisitaForm?<section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><div className="text-xs font-extrabold uppercase text-[#2F5597]">Nova visita</div><h2 className="mt-1 text-2xl font-extrabold">{atual?.nomeFantasia}</h2><p className="text-sm text-slate-500">Esta visita ficará vinculada automaticamente à empresa ativa.</p></div><button onClick={()=>setShowVisitaForm(false)} className="rounded-xl bg-slate-100 px-3 py-2 font-bold">Fechar</button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-xs font-bold text-slate-500">Data da visita</span><input type="date" className="w-full rounded-xl border p-3" value={vf.data} onChange={e=>setVf({...vf,data:e.target.value})}/></label><label><span className="mb-1 block text-xs font-bold text-slate-500">Responsável pela visita</span><input className="w-full rounded-xl border p-3" value={vf.responsavel} onChange={e=>setVf({...vf,responsavel:e.target.value})}/></label><label className="md:col-span-2"><span className="mb-1 block text-xs font-bold text-slate-500">Observações iniciais</span><textarea rows={4} className="w-full rounded-xl border p-3" value={vf.observacoes} onChange={e=>setVf({...vf,observacoes:e.target.value})}/></label></div><button onClick={salvarVisita} disabled={criandoVisita} className="mt-5 w-full rounded-xl bg-[#2F5597] p-3 font-extrabold text-white disabled:opacity-50">{criandoVisita?"Criando...":"Criar visita"}</button></section>
   :view==="visita"&&visitaAtual?<section className="space-y-4"><div className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:justify-between"><div><div className="text-xs font-extrabold uppercase text-[#2F5597]">Central da Visita</div><h1 className="mt-1 text-2xl font-extrabold">{empresaVisita?.nomeFantasia}</h1><div className="mt-1 text-sm text-slate-500">{fdata(visitaAtual.data)}{visitaAtual.responsavel?` • ${visitaAtual.responsavel}`:" • Responsável não informado"}</div></div><button onClick={()=>setView("visitas")} className="rounded-xl bg-slate-100 px-4 py-2 font-bold">Voltar</button></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>Progresso da visita</span><span>{visitaAtual.progresso||0}%</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#2F5597]" style={{width:`${visitaAtual.progresso||0}%`}}/></div></div></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[["Etapa 1","Ambientes","Selecione os setores que serão avaliados nesta visita."],["Etapa 2","Checklist","Avaliação guiada por ambiente e critérios técnicos."],["Evidências","Fotos e áudio","Registros de campo vinculados à visita."],["Resultado","Não conformidades","Pendências, risco, legislação e ação corretiva."],["Gestão","Plano de ação","Responsáveis, prazos e acompanhamento."],["Encerramento","Relatório","Revisão e geração do documento final."]].map((x,i)=><div key={x[1]} className={`rounded-2xl bg-white p-5 shadow-sm ${i===0?"border-2 border-[#2F5597]":"opacity-70"}`}><div className="text-xs font-extrabold uppercase text-slate-400">{x[0]}</div><div className="mt-2 text-xl font-extrabold">{x[1]}</div><p className="mt-1 text-sm text-slate-500">{x[2]}</p>{i===0&&<div className="mt-4 font-extrabold text-[#2F5597]">Próxima etapa →</div>}</div>)}</div></section>
   :view==="inicio"?<div className="space-y-4"><section className="rounded-2xl bg-gradient-to-r from-[#17365D] to-[#2F5597] p-5 text-white shadow-sm"><div className="text-xs font-extrabold uppercase text-blue-100">Painel da consultoria</div><h1 className="mt-2 text-3xl font-extrabold">Operação em campo</h1></section><section className="grid grid-cols-2 gap-3 md:grid-cols-4"><MetricCard label="Empresas" value={Object.keys(db.empresas).length}/><MetricCard label="Visitas" value={db.visitas.length}/><MetricCard label="Em andamento" value={db.visitas.filter(v=>v.status==="Em andamento").length}/><MetricCard label="Concluídas" value={db.visitas.filter(v=>v.status==="Concluída").length}/></section></div>
   :view==="empresas"?<section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h1 className="text-2xl font-extrabold">Empresas</h1><p className="text-sm text-slate-500">Cadastre e selecione seus clientes.</p></div><button onClick={()=>setShowEmpresaForm(true)} className="rounded-xl bg-[#2F5597] px-4 py-3 font-extrabold text-white">+ Nova empresa</button></div><div className="mt-4 grid gap-3 md:grid-cols-2">{Object.values(db.empresas).map(e=><div key={e.id} className={`rounded-xl border p-4 ${db.empresaAtualId===e.id?"border-[#2F5597] bg-blue-50":""}`}><div className="font-extrabold">{e.nomeFantasia}</div><div className="text-sm text-slate-500">{e.razaoSocial}</div><div className="mt-4 flex gap-2"><button onClick={()=>setDb(o=>({...o,empresaAtualId:e.id}))} className="flex-1 rounded-xl bg-slate-100 px-4 py-2 font-bold">{db.empresaAtualId===e.id?"Empresa ativa":"Selecionar"}</button>{db.empresaAtualId===e.id&&<button onClick={novaVisita} className="rounded-xl bg-[#2F5597] px-4 py-2 font-bold text-white">Nova visita</button>}</div></div>)}</div></section>
   :<section className="space-y-4"><div className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><div className="text-xs font-extrabold uppercase text-[#2F5597]">Módulo Visitas</div><h1 className="mt-1 text-2xl font-extrabold">Visitas técnicas</h1></div><button onClick={novaVisita} disabled={!atual} className="rounded-xl bg-[#2F5597] px-4 py-3 font-extrabold text-white disabled:opacity-40">+ Nova visita</button></div></div><div className="grid gap-4 lg:grid-cols-2">{visitas.map(v=>{const e=db.empresas[v.empresaId];return <article key={v.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between"><div><div className="text-xs font-extrabold uppercase text-slate-400">{fdata(v.data)}</div><h2 className="mt-1 text-xl font-extrabold">{e?.nomeFantasia}</h2><p className="text-sm text-slate-500">{v.responsavel||"Responsável não informado"}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-extrabold text-amber-700">{v.status}</span></div><div className="mt-5 flex gap-2">{v.status==="Em andamento"?<><button onClick={()=>continuar(v.id)} className="flex-1 rounded-xl bg-[#17365D] px-4 py-2 font-bold text-white">Continuar visita</button><button onClick={()=>concluir(v.id)} className="rounded-xl bg-emerald-50 px-4 py-2 font-bold text-emerald-700">Concluir</button></>:<button onClick={()=>reabrir(v.id)} className="flex-1 rounded-xl bg-slate-100 px-4 py-2 font-bold">Reabrir visita</button>}<button onClick={()=>excluir(v.id)} className="rounded-xl bg-red-50 px-4 py-2 font-bold text-red-700">Excluir</button></div></article>})}</div></section>}
  </div>
 </div>
}